akun/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import AkunAutocomplete

from . import views

# app_name = 'akun'
urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),
    
    path('edit/', views.edit, name='edit'),
    path('add/', views.input_profil, name='add'),

    path('autocomplete/', AkunAutocomplete.as_view(), name='user-autocomplete'),
]

master_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_view
# from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('akun.urls')),
    
    path('hcp/', include('human_capital.urls', namespace='hcp')),
    path('stockopname/', include('stockopname.urls', namespace='stockopname')),
    path('antrian/', include('antol.urls')),
    path('winback/',include('winback.urls')),
    path('assets/',include('inventaris_apps.urls', namespace='aset')),
    path('kepesertaan/',include('menu_kepesertaan.urls', namespace='kepesertaaan')),
    path('', views.index, name='home'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

winback/urls.py
from django.urls import path

from . import views

app_name = 'winback'
urlpatterns = [
    path('input/pekerjaan/', views.InputJenis,name='input_jenis'),
    path('input/lokasi/',views.InputLokasi,name='input_lokasi'),
    path('daftar/',views.DaftarTK, name='daftar_tk'),
    path('list/pekerjaan/', views.DaftarJenis, name='list_jenis'),
    path('list/lokasi/',views.DaftarLokasi, name='list_lokasi'),
    path('upload/lokasi/', views.upload_lokasi, name='upload_lokasi'),
    path('upload/pekerjaan/', views.upload_pekerjaan, name='upload_pekerjaan'),
    path('xls/', views.export_xls,name='export_xls'),
    path('',views.ListTK,name='home'),
]

winback/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
KODE_PAKET = (
    ('T','JKK,JKM'),
    ('L','JKK,JKM,JHT')
)

KODE_IURAN = (
    (1,'1 BLN'),
    (3,'3 BLN'),
    (6,'6 BLN'),
    (12,'12 BLN')
)

class LokasiPekerjaan(models.Model):
    kode = models.CharField(max_length=4)
    nama_kota = models.CharField(max_length=50)

    def __str__(self):
        return self.nama_kota

class JenisPekerjaan(models.Model):
    kode = models.CharField(max_length=4)
    nama_pekerjaan = models.CharField(max_length=50)

    def __str__(self):
        return self.nama_pekerjaan
        

class daftar(models.Model):
    nik = models.CharField(max_length=16)
    nama = models.CharField(max_length=50)
    tgl_lahir = models.DateField(default=timezone.now)
    # tgl_lahir = models.CharField(max_length=10)
    no_hp = models.CharField(max_length=13)
    surel = models.EmailField(blank=True, null=True)
    jenis_pekerjaan =  models.ForeignKey(JenisPekerjaan, on_delete=models.CASCADE)
    jenis_pekerjaan2 = models.ForeignKey(JenisPekerjaan, on_delete=models.CASCADE, related_name='jenis2',null=True, blank=True)
    lokasi_pekerjaan = models.ForeignKey(LokasiPekerjaan, on_delete=models.CASCADE)
    upah = models.IntegerField()
    kode_paket = models.CharField(max_length=1, choices=KODE_PAKET)
    kode_iuran = models.IntegerField(choices=KODE_IURAN)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def total(self):
        if self.kode_paket == 'T':
            jkm = 6800
            jkk = self.upah * 0.01
            self.total = self.kode_iuran * (jkk+jkm)
        else:
            jkm = 6800
            jkk = self.upah * 0.01
            jht = self.upah * 0.02
            self.total = self.kode_iuran * (jkm+jkk+jht)

        return self.total

            

winback/forms.py
from django import forms

from .models import LokasiPekerjaan, JenisPekerjaan, daftar

class LokasiForm(forms.ModelForm):
    class Meta:
        model = LokasiPekerjaan
        fields = ('__all__')

        widgets = {
            'kode':forms.TextInput(
                attrs={'class':'form-control'}),
            'nama_kota':forms.TextInput(
                attrs={'class':'form-control'}),
        }

class JenisForm(forms.ModelForm):
    class Meta:
        model = JenisPekerjaan
        fields = (
            'kode','nama_pekerjaan'
        )

        widgets = {
            'kode':forms.TextInput(
                attrs={'class':'form-control'}),
            'nama_pekerjaan':forms.TextInput(
                attrs={'class':'form-control'}),
        }

class DaftarForm(forms.ModelForm):
    class Meta:
        model = daftar
        fields = (
            'nik','nama','tgl_lahir',
            'no_hp','surel','jenis_pekerjaan',
            'jenis_pekerjaan2','lokasi_pekerjaan','upah',
            'kode_paket','kode_iuran'
        )

        widgets = {
            'nik':forms.TextInput(
                attrs={'class':'form-control', 'id':'nik'}),
            'nama':forms.TextInput(
                attrs={'class':'form-control'}),
            'tgl_lahir':forms.TextInput(
                attrs={'class':'form-control','type':'date'}),
            'no_hp':forms.TextInput(
                attrs={'class':'form-control'}),
            'surel':forms.EmailInput(
                attrs={'class':'form-control'}),
            'jenis_pekerjaan':forms.Select(
                attrs={'class':'form-control'}),
            'jenis_pekerjaan2':forms.Select(
                attrs={'class':'form-control'}),
            'lokasi_pekerjaan':forms.Select(
                attrs={'class':'form-control'}),
            'upah':forms.TextInput(
                attrs={'class':'form-control'}),
            'kode_paket':forms.Select(
                attrs={'class':'form-control'}),
            'kode_iuran':forms.Select(
                attrs={'class':'form-control'}),
        }

winback/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
# from datetime import datetime
from django.conf import settings

import io,csv,xlwt

# Create your views here.
from .forms import JenisForm, LokasiForm, DaftarForm
from .models import LokasiPekerjaan, JenisPekerjaan, daftar

def InputJenis(request):
    if request.method == 'POST':
        form = JenisForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

            return redirect('winback:input_jenis')
    else:
        form = JenisForm()
    return render(request,'winback/input_jenis.html',{'form':form})

def InputLokasi(request):
    if request.method == 'POST':
        form = LokasiForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('winback:input_lokasi')
    else:
        form = LokasiForm()
    return render(request,'winback/input_lokasi.html',{'form':form})

def DaftarTK(request):
    
    if request.method == 'POST':
        form = DaftarForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            # cek = request.POST.get('nik')
            post.save()

            return redirect('winback:daftar_tk')
    else:
        form = DaftarForm()
    return render(request,'winback/daftar_tk.html',{'form':form})

def DaftarLokasi(request):
    
    context = {
        'datas':LokasiPekerjaan.objects.all()
    }

    return render(request,'winback/lokasi.html',context)

def DaftarJenis(request):
    context = {
        'datas':JenisPekerjaan.objects.all()
    }

    return render(request,'winback/pekerjaan.html',context)

def ListTK(request):
    datas = daftar.objects.all()

    return render(request,'winback/index.html',{'datas':datas})

def upload_pekerjaan(request):
    datas = JenisPekerjaan.objects.all()
    datas = 'Harus sesuai format'
    if request.method == 'GET':
        return render(request, 'winback/upload_pekerjaan.html', {'datas': datas})
    csv_file = request.FILES['file']
    # print(csv_file.size)
    # tgl = request.POST['tgl']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'File harus format CSV')

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

    for column in csv.reader(io_string, delimiter=','):

        _,  created = JenisPekerjaan.objects.update_or_create(
            kode=column[0],
            nama_pekerjaan=column[1],
            
        )

    context = {}
    return render(request, 'winback/upload_pekerjaan.html', context)

def upload_lokasi(request):
    datas = LokasiPekerjaan.objects.all()
    datas = 'Harus sesuai format'
    if request.method == 'GET':
        return render(request, 'winback/upload_lokasi.html', {'datas': datas})
    csv_file = request.FILES['file1']
    # print(csv_file.size)
    # tgl = request.POST['tgl']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'File harus format CSV')

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

    for column in csv.reader(io_string, delimiter=','):

        _,  created = LokasiPekerjaan.objects.update_or_create(
            kode=column[0],
            nama_kota=column[1],
            
        )

    context = {}
    return render(request, 'winback/upload_lokasi.html', context)

def export_xls(request):
    response = HttpResponse(content_type='text/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="TEMPLATE_PENDAFTARAN_BPU_TK_BARU_A0200001_000.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Pendaftaran TK Baru BPU')
    
    ws.write(0,2,'Format: DD-MM-YYYY')
    ws.write(0,3,"FORMAT: Diawali '08'")
    ws.write(0,5,'List Jenis Pekerjaan')
    ws.write(0,6,'List Jenis Pekerjaan')
    ws.write(0,7,'List Lokasi Pekerjaan')
    ws.write(0,9,'List Kode Paket')
    ws.write(0,10,'List Bulan Iuran')

    style1 = xlwt.easyxf(num_format_str='DD-MM-YYYY')

    row_num = 1
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Nomor Identitas*','Nama Lengkap*','Tgl. Lahir*','Handphone*','Email','Jenis Pekerjaan 1*',
                'Jenis Pekerjaan 2','Lokasi Pekerjaan*','Upah*','Kode Paket*','Bulan Iuran*',]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = daftar.objects.all().values_list('nik','nama','tgl_lahir','no_hp','surel','jenis_pekerjaan__kode',
                                            'jenis_pekerjaan2__kode','lokasi_pekerjaan__kode','upah','kode_paket','kode_iuran')

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            if col_num == 2:
                ws.write(row_num, col_num, row[col_num], style1)
            else:
                ws.write(row_num, col_num, row[col_num], font_style)
    wb.save(response)
    return response

winback/templates/winback/daftar_tk.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Pendaftaran TK Winback
{% endblock title %}

{% block style %}
{% endblock style %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="{% url 'home' %}">Dashboard</a></li>
                            <li class="active">Pendaftaran TK</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
<div class="animated fadeIn">
    <!-- Animated -->
    <div class="row">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">Pendaftaran TK Winback</strong>
                        </div>
                    </div>
                </div>
                <div class="card-body card-block">
                    <form method="post">
                    {% csrf_token %}
                    {% if form.subject.errors %}
                        <ol role="alertdialog">
                            {% for error in form.subject.errors %}
                            <li role="alert"><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">NIK</label> 
                            <div class="col-sm-6">
                                    {{form.nik}}
                            
                            </div>
                            <div class="row-2">
                                <button type="button" id="cek">Cek NIK</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Nama Lengkap</label> 
                            <div class="col-sm-6">
                                    {{form.nama}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Tgl. Lahir</label> 
                            <div class="col-sm-4">
                                    {{form.tgl_lahir}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">No. Handphone</label> 
                            <div class="col-sm-4">
                                    {{form.no_hp}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Email</label> 
                            <div class="col-sm-4">
                                    {{form.surel}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Jenis Pekerjaan I</label> 
                            <div class="col-sm-6">
                                    {{form.jenis_pekerjaan}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Jenis Pekerjaan 2</label> 
                            <div class="col-sm-6">
                                    {{form.jenis_pekerjaan2}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Lokasi Pekerjaan</label> 
                            <div class="col-sm-6">
                                    {{form.lokasi_pekerjaan}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Upah</label> 
                            <div class="col-sm-4">
                                    {{form.upah}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Kode Paket</label> 
                            <div class="col-sm-4">
                                    {{form.kode_paket}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Kode Iuran</label> 
                            <div class="col-sm-4">
                                    {{form.kode_iuran}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="offset-8 col-6">
                            <button name="submit" type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>


<script>
$(document).ready(function(){
    $("#cek").click(function(){
        
        var str = $("#nik").val();
        var url = "http://smile.bpjsketenagakerjaan.go.id/smile/mod_kn/ajax/kn5000_detail.php?NIK="+str
        window.open(url, '_blank')
    });
});
</script>
{% endblock script %}

winback/templates/winback/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
Aplikasi TK Winback Kacab Langsa
{% endblock title %}

{% block style %}
{% endblock style %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="{% url 'home' %}">Dashboard</a></li>
                            <li class="active">Daftar TK Winback</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
    <div class="animated fadeIn">
    <!-- Animateda -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">List TK Winback</strong>
                        </div>
                        
                        
                    </div>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table" id="contoh">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th>NIK</th>
                                    <th>NAMA</br>LENGKAP</th>
                                    <th>TGL</br>LAHIR</th>
                                    <th>NO</br>HANDPHONE</th>
                                    <th>EMAIL</th>
                                    <th>JENIS</br>PEKERJAAN 1</th>
                                    
                                    <th>LOKASI</br>PEKERJAAN</th>
                                    <th>UPAH</th>
                                    <th>PAKET</th>
                                    <th>IURAN</th>
                                    <th>TOTAL</br>IURAN</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in datas %}
                                <tr>
                                    <td class="serial">{{forloop.counter}}</td>
                                    <td>{{data.nik}}</td>
                                    <td>{{data.nama}}</td>
                                    <td>{{data.tgl_lahir}}</td>
                                    <td>{{data.no_hp}}</td>
                                    <td id="email">{{data.surel}}</td>
                                    <td>
                                        {% if data.jenis_pekerjaan2 is None %}
                                            {{data.jenis_pekerjaan}}
                                        {% else %}
                                            {{data.jenis_pekerjaan}}</br>{{data.jenis_pekerjaan2}}
                                        {% endif %}</td>
                                    <td>{{data.lokasi_pekerjaan}}</td>
                                    <td>RP.{{data.upah|intcomma}}
                                    <td>{{data.get_kode_paket_display}}</td>
                                    <td>{{data.get_kode_iuran_display}}</td>
                                    <td>Rp. {{data.total|intcomma}}
                                </tr>
                                
                                {% endfor %}
                            </tbody>
                            
                        </table>
                    </div>
                    <div class="col-12">
                        <a href="{% url 'winback:export_xls' %}" class="btn btn-primary">Export</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/jquery-3.5.1.js' %}" type="text/javascript"></script>

<script>
$(document).ready(function(){
    
    $("#email").each( function(){
    $(this).html();
});
});

</script>

{% endblock script %}

winback/templates/winback/input_jenis.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Form Input Jenis Pekerjaan
{% endblock title %}

{% block style %}

{% endblock style %}

{% block breadcrumbs %}
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
<div class="animated fadeIn">
    <!-- Animated -->
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">Input Jenis Pekerjaan</strong>
                        </div>
                    </div>
                </div>
                <div class="card-body card-block">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Nama Pekerjaan</label> 
                            <div class="col-sm-8">
                                    {{form.nama_pekerjaan}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-2 col-form-label" for="kode">Kode Pekerjaan</label> 
                            <div class="col-sm-8">
                                    {{form.kode}}
                                
                            </div>
                        </div> 
                        <div class="form-group row">
                            <div class="col-12">
                            <a href="{% url 'winback:upload_pekerjaan' %}">Upload</a>
                            </div>
                            <div class="offset-8 col-6">
                            <button name="submit" type="submit" class="btn btn-primary" data-toggle="modal" data-target="sideModalBL">Submit</button>
                            </div>
                            <!-- To change the direction of the modal animation change .right class -->
                            <div class="modal fade right" id="sideModalBL" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                            aria-hidden="true">

                            <!-- Add class .modal-side and then add class .modal-top-right (or other classes from list above) to set a position to the modal -->
                            <div class="modal-dialog modal-side modal-bottom-left" role="document">


                                <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title w-100" id="myModalLabel">Simpan Data</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    ...
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Save changes</button>
                                </div>
                                </div>
                            </div>
                            </div>
                            <!-- Side Modal Top Right -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>


{% endblock content %}

winback/templates/winback/input_lokasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Input Lokasi Pekerjaan
{% endblock title %}

{% block style %}

{% endblock style %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="{% url 'home' %}">Dashboard</a></li>
                            <li class="active">Input Lokasi</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
<div class="animated fadeIn">
    <!-- Animated -->
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">Form Input Lokasi Pekerjaan</strong>
                        </div>
                    </div>
                </div>
                <div class="card-body card-block">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group row">
                            <label class=" col-2 col-form-label">Nama Kota</label> 
                            <div class="col-sm-8">
                                    {{form.nama_kota}}
                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-2 col-form-label" for="kode">Kode Kota</label> 
                            <div class="col-sm-8">
                                    {{form.kode}}
                                
                            </div>
                        </div> 
                        <div class="form-group row">
                            <div class="col-12">
                            <a href="{% url 'winback:upload_lokasi' %}">Upload</a>
                            </div>
                            <div class="offset-8 col-6">
                            
                            <button name="submit" type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- test -->
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">Petunjuk Penggunaan</strong>
                        </div>
                    </div>
                </div>
                <div class="card-body card-block">
                    
                </div>
            </div>
        </div>
        <!-- akhir test -->
    </div>
    
    </div>
</div>


{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
{% endblock script %}