akun/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import AkunAutocomplete

from . import views

# app_name = 'akun'
urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),
    
    path('edit/', views.edit, name='edit'),
    path('add/', views.input_profil, name='add'),

    path('autocomplete/', AkunAutocomplete.as_view(), name='user-autocomplete'),
]

human_capital/urls.py
from django.urls import path

from human_capital.views import UserAutocomplete

from . import views

app_name = 'hcp'
urlpatterns = [
    path('',views.index,name='home'),
    path('karyawan/karir/',views.karir, name='karir'),
    path('tambah/karyawan/', views.tambah_k, name='tambah_k'),
    path('karyawan/detail/<int:pk>/', views.detail_k, name='detail_k'),
    path('karyawan/edit/<int:pk>/', views.edit_k, name='edit_k'),
    path('karyawan/hapus/<int:pk>/',views.hapus_k, name='hapus_k'),
    path('karyawan/karir/tambah/', views.tambah_karir, name='tambah_karir'),
    path('autocomplete/', UserAutocomplete.as_view(), name='profil_autocomplete'),
]

master_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_view
# from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('akun.urls')),
    
    path('hcp/', include('human_capital.urls', namespace='hcp')),
    path('stockopname/', include('stockopname.urls', namespace='stockopname')),
    path('antrian/', include('antol.urls')),
    path('winback/',include('winback.urls')),
    path('assets/',include('inventaris_apps.urls', namespace='aset')),
    path('kepesertaan/',include('menu_kepesertaan.urls', namespace='kepesertaaan')),
    path('', views.index, name='home'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

human_capital/models.py
from django.db import models
from django.contrib.auth.models import User
from akun.models import Profil
from django.conf import settings
from django.core.validators import RegexValidator
from datetime import timedelta
import datetime, time

GOL_DARAH = (
    (1,'A'),
    (2,'B'),
    (3,'AB'),
    (4,'O'),
)

STATUS = (
    (1,'Menikah'),
    (2,'Belum Menikah'),
)

STATUS_KARIR = (
    (1,'Permanent'),
    (2,'Unpermanent'),
)

JOBDESK = [
    (1,(
        (1,'Kabid Kepesertaan'),
        (2,'Kabid Pelayanan'),
    )
    ),
]

UNIT_KERJA = [
    ('A09','Kacab Langsa')
]

class Karyawan(models.Model):
    # karyawan = models.OneToOneField(settings.AUTH_USER_MODEL,
    #                             on_delete=models.CASCADE)

    karyawan = models.ForeignKey(Profil, on_delete=models.CASCADE, related_name='username')
    
    nik = models.CharField(max_length=16, validators=[RegexValidator('^((1[1-9])|(21)|([37][1-6])|(5[1-4])|(6[1-5])|([8-9][1-2]))[0-9]{2}[0-9]{2}(([0-6][0-9])|(7[0-1]))((0[1-9])|(1[0-2]))([0-9]{2})[0-9]{4}$',
        message="Format NIK harus 16 Angka")])
    tgl_lhr = models.DateField()
    gol_darah = models.IntegerField(choices=GOL_DARAH)
    alamat = models.TextField(max_length=300)
    status = models.IntegerField(choices=STATUS, blank=True, null=True)
    istri = models.CharField(max_length=50, null=True, blank=True)
    tgl_i = models.DateField(null=True, blank=True)
    anak_1 = models.CharField(max_length=50, blank=True, null=True)
    tgl_lhr_1 = models.DateField(null=True, blank=True)
    anak_2 = models.CharField(max_length=50, blank=True, null=True)
    tgl_lhr_2 = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nik
        
class Karir(models.Model):
    karyawan_k = models.ForeignKey(Karyawan, on_delete=models.CASCADE)
    status_karir = models.IntegerField(choices=STATUS_KARIR)
    tgl_efektif = models.DateField()
    job_desk = models.IntegerField(choices=JOBDESK)
    unit_kerja = models.CharField(max_length=3, choices=UNIT_KERJA)
    
    def masa_kerja(self):
        
        selisih = datetime.date.today() - self.tgl_efektif
        tahun = datetime.date.today().year
                        
        if (tahun % 4) or (tahun % 400) == 0:
            selisih_y = int(selisih.days/366)
            selisih_b = (selisih.days % 366) % 12
                        
        else:
            selisih_y = int(selisih.days/365)
            selisih_b = (selisih.days % 365) % 12
            
        return '{} Tahun {} Bulan'.format(selisih_y, (selisih_b))


    

    # def status_bldp(self):
    #     if self.masa_kerja < 1826.25:
    #         return 'T'
    #     else:
    #         return 'Y'                                                                                                                                                                                                                                                                                                                                                                  

human_capital/forms.py
from django import forms
from dal import autocomplete

from .models import Karyawan, Karir

class KaryawanForm(forms.ModelForm):
    class Meta:
        model = Karyawan
        fields = (
            'karyawan','nik','tgl_lhr',
            'gol_darah','alamat','status','istri',
            'tgl_i','anak_1','tgl_lhr_1',
            'anak_2','tgl_lhr_2'
        )

        widgets = {
            'karyawan': autocomplete.ModelSelect2(
                url='hcp:profil_autocomplete'),
            
            # 'karyawan':forms.TextInput(
            #     attrs={'class':'form-control',
            #         'id':'tags', 'name':'karyawan'}),
            'nik':forms.TextInput(
                attrs={'class':'form-control',
                    'name':'nik'}),
            'tgl_lhr':forms.TextInput(
                attrs={'class':'form-control',
                    'type':'date','name':'tgl'}),
            'gol_darah':forms.Select(
                attrs={'class':'form-control',
                    'name':'gol'}),
            'alamat':forms.TextInput(
                attrs={'class':'form-control',
                    'placeholder':'Input Alamat', 'name':'alamat'}),
            'status':forms.Select(
                attrs={'class':'form-control'}),
            'nama_istri':forms.TextInput(
                attrs={'class':'form-control',
                    'placeholder':'Input Nama Istri'}),
            'tgl_i':forms.TextInput(
                attrs={'class':'form-control',
                    'id':'buttons-exmaple','type':'date'}),
            'anak_1':forms.TextInput(
                attrs={'class':'form-control',
                    'placeholder':'Input Nama Anak Pertama'}),
            'tgl_lhr_1':forms.DateInput(
                attrs={'class':'form-control','type':'date'}),
            'anak_2':forms.TextInput(
                attrs={'class':'form-control',
                    'placeholder':'Input Nama Anak Kedua'}),
            'tgl_lhr_2':forms.DateInput(
                attrs={'class':'form-control','type':'date'}),
        }

class KarirForm(forms.ModelForm):
    class Meta:
        model = Karir
        fields = (
            'karyawan_k','status_karir','tgl_efektif',
            'job_desk','unit_kerja'
        )
        
        widgets = {
            # 'karyawan_k':autocomplete.ModelSelect2(
                # url='hcp:profil_autocomplete'),
            'karyawan_k':forms.Select(
                attrs={'class':'form-control', 'disabled':'disabled'}),
            'status_karir':forms.Select(
                attrs={'class':'form-control'}),
            'tgl_efektif':forms.DateInput(
                attrs={'class':'form-control', 'type':'date'}),
            'job_desk':forms.Select(
                attrs={'class':'form-control'}),
            'unit_kerja':forms.Select(
                attrs={'class':'form-control'}),
        }

human_capital/views.py
from dal import autocomplete

from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from .models import Karyawan, Karir
from django.contrib.auth.models import User
from akun.models import Profil
from .forms import KaryawanForm, KarirForm


def KaryawanAutocomplete(request):
    if 'term' in request.GET:
        qs = User.objects.filter(username__icontains=request.GET.get('term'))
        # print(qs)
        names = list()
        for profil in qs:
            # names.append(profil.id)
            names.append(profil.username)
        return JsonResponse(names, safe=False)


def index(request):

    cuser = request.user
    admin = User.objects.filter(username=cuser, is_superuser=True)
    
    if admin:
        datas = Karyawan.objects.all().order_by('karyawan__user')
    else:
        datas = Karyawan.objects.select_related('karyawan__user').filter(karyawan__user__username=cuser)

    return render(request,'human_capital/karyawan/karyawan.html', {'datas':datas, 'cuser':cuser})

def hapus_k(request, pk):
    data_k = get_object_or_404(Karyawan, pk=pk)
    if data_k.gambar:
        data_k.gambar.delete()
    data_k.delete()
    return redirect('home:hcp')

def edit_k(request, pk):
    data_k = get_object_or_404(Karyawan, pk=pk)
    if request.method == 'POST':
        form = KaryawanForm(request.POST, request.FILES, instance=data_k)
        if form.is_valid():
            data_k = form.save(commit=False)
            data_k.save()
            return redirect('hcp:home')
    else:
        form = KaryawanForm(instance=data_k)
    return render(request,
                  'human_capital/keluarga/edit_k.html',
                  {'form': form,
                   'data_k': data_k})

def detail_k(request, pk):
    
    data_k = get_object_or_404(Karyawan, pk=pk)
    
    context = {
        # 'gbr': Profil.objects.all(),
        'data_k': data_k,
        
    }
    return render(request, 'human_capital/keluarga/detail_k.html', context)
    
def karir(request):

    cuser = request.user
    
    datas = Karir.objects.select_related('karyawan_k__karyawan__user').filter(karyawan_k__karyawan__user__username=cuser)
    
    context = {
        'cuser':cuser,
        'datas': datas,
       }
    return render(request,'human_capital/karir.html', context)

def tambah_karir(request):
    # cuser = request.user
    # kar = get_object_or_404(Karyawan, pk=pk)
    if request.method == 'POST':
        form = KarirForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            # post['user'] = cuser
            post.save()
            return redirect('hcp:karir')
    else:
        form = KarirForm()
    return render(request,'human_capital/tambah_karir.html', {'form':form})

def tambah_k(request):
    # reqs = request.POST.get('karyawan')
    # print(q)
    if request.method == 'POST':
        form = KaryawanForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('hcp:home')
    else:
        form = KaryawanForm()
        
    return render(request,'human_capital/karyawan/tambah_k.html',{'form':form})

class UserAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Profil.objects.none()

        data_user = Profil.objects.all()

        if self.q:
            data_user = data_user.filter(nama__icontains=self.q).order_by('id')
            # data_user = data_user.filter(full_name__icontains=self.q)
        return data_user 

human_capital/templates/human_capital/karyawan/karyawan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Daftar Karyawan Kacab Langsa{% endblock title %}

{% block style %}
{% endblock style %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="{% url 'home' %}">Dashboard</a></li>
                            <li class="active">Daftar Karyawan</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
    <!-- Animated -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">List Karyawan</strong>
                        </div>
                        {% if user.is_superuser %}
                        <div class="col" align="right">
                            <a href="{% url 'hcp:tambah_k' %}" class="btn btn-primary btn-sm"
                                role="button">Tambah</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body--">
                    <div class="table-responsive">
                    <table class="table table-fixed" id="dtBasicExample">
                        <thead>
                        <tr align="center">
                            <th scope="col">#</th>
                            <th scope="col" class="avatar">Foto</th>
                            <th scope="col">Nama</th>
                            <th scope="col">NIK</th>
                            <th scope="col">Tgl. Lahir</th>
                            <th scope="col">Gol. Darah</th>
                            <th scope="col">Alamat</th>
                            {% if user.is_superuser %}
                            <th scope="col">Aksi</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for data in datas %}
                        <tr align="center">
                            <th scope="row" class="serial">{{ forloop.counter }}</th>
                            <td class="avatar">
                                <div class="round-img">
                                    <a href="#"><img class="rounded-circle" width="50px" height="50px"
                                                    src="{% if data.karyawan.photo %}{{data.karyawan.photo.url}}{% else %}#{% endif %}"
                                                        alt=""></a>
                                </div>
                            </td>
                            <td><a href="{% url 'hcp:detail_k' pk=data.pk %}">{{ data.karyawan.nama }}</a></td>
                            <td>{{ data.nik }}</td>
                            <td>{{ data.tgl_lhr }}</td>
                            <td>{{ data.get_gol_darah_display }}</td>
                            <td>{{ data.alamat|linebreaksbr }}</td>
                            
                            {% if user.is_superuser %}
                            <td>
                                        <a href="{% url 'hcp:edit_k' pk=data.pk %}"><i class="fa fa-pencil"></i>
                                            edit</a> |
                                        <a href="#" data-toggle="modal" data-target="#staticModal{{ data.pk }}"><i
                                                class="fa fa-trash-o"></i>
                                            hapus</a>
                            </td>
                            {% endif %}
                        </tr>
                            <div class="modal fade" id="staticModal{{ data.pk }}" tabindex="-1" role="dialog"
                                aria-labelledby="staticModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <div class="alert alert-danger" role="alert">
                                                <h5 class="modal-title" id="staticModalLabel">Peringatan</h5>
                                            </div>
                                            <button type="button" class="close" data-dismiss="modal"
                                                aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>
                                                Apakah anda ingin menghapus data {{ data.karyawan.nama }}?
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary btn-sm"
                                                data-dismiss="modal">Batal</button>
                                            <a class="btn btn-danger btn-sm" role="button"
                                                href="{% url 'hcp:hapus_k' pk=data.pk %}">Iya</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}

<script>
// Basic example
    $(document).ready(function () {
    $('#dtBasicExample').DataTable({
        "paging": true,
        "pagingType": "simple" // "simple" option for 'Previous' and 'Next' buttons only
    });
    $('.dataTables_length').addClass('bs-select');
    });
</script>

{% endblock script %}

human_capital/templates/human_capital/karyawan/tambah_k.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Human Capital - Tambah Karyawan
{% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/select2.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/dist/css/select2.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'js/jquery-ui.css' %}"> {% endcomment %}
{% endblock style %}

{% block content %}
<div class="content">
    <div class="animated fadeIn">

        <div class="row">
                    
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">Input Karyawan</div>
                    <div class="card-body card-block">
                        <form method="post" class="">
                            {% csrf_token %}
                            
                            {{form|crispy}}
                            
                            <div class="row m-0">
                                <div class="col" align="right">
                                    <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
                                    <a href="{% url 'hcp:home' %}" class="btn btn-primary btn-sm"
                                        role="button">Batal</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>


    </div><!-- .animated -->
</div><!-- .content -->
{% endblock content %}

{% block script %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/select2/dist/js/select2.full.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/forward.js' %}"></script>


{% endblock script %}